### PR TITLE
WIP: Typescript Refactor

### PR DESCRIPTION
**Pull request by fratzinger**
BREAKING CHANGES included.

- removed 'orders' service, because stripe v11 removed it, see: https://github.com/stripe/stripe-node/blob/master/CHANGELOG.md#1100---2022-11-16
- removed 'sku' service, because stripe v11 removed it, see: https://github.com/stripe/stripe-node/blob/master/CHANGELOG.md#1100---2022-11-16
- uses feathers v5 as dependency

### CODE REVIEW

**Comment by DaddyWarbucks** [comment]
Want me to wait to merge this?

**Comment by DaddyWarbucks** [comment]
Sorry. Accidentally hit "Close with comment" instead of just "Comment".

**Comment by fratzinger** [comment]
Definitely wait! Putting "WIP" in front of the title does not make it a draft on github?! I'll let you know, when I think it's ready.

**Comment by daffl** [comment]
I think you have to explicitly open it as a draft PR but you should also be able to turn it into a draft in the sidebar on the left. Anyway, sorry for jumping into the conversation, see you in two days @fratzinger (I'm in Düsseldorf now which is basically 80% of the way 😄)!

**Comment by fratzinger** [comment]
I'll merge this into branch `dove` now and continue from there. Hopefully we will have CI then. I'll open a new PR with that branch.

**Pull request merged**
