### PR TITLE
Add params to remove method for Subscriptions

### LINKED ISSUE #40: Can't pass params to .remove calls
Hey @daffl 

Only one parameter is accepted in `.remove(id)` calls.
This of course means I have to use the services' Stripe object directly (which is fine for now!)

For instance, I want to write the following:

```js
subscriptionsService.remove(subscription.id, { at_period_end: true })
```

But instead, I have to write:

```js
subscriptionsService.stripe.subscriptions.del(subscription.id, { at_period_end: true })
```

Example of a `.remove` call that only accepts an `id` with no `params`

https://github.com/feathersjs-ecosystem/feathers-stripe/blob/master/lib/services/subscription.js#L28

I'm happy to send a PR if you think this should be added.

Cheers 😀

### PR DESCRIPTION
**Pull request by wdmtech**
Fixes #40 by allowing passing of params to the remove method for Stripe Subscriptions

### CODE REVIEW

**Comment by daffl** [comment]
Thank you! Would you mind adding this to the other calls in the service that take those options as well?

**Comment by wdmtech** [comment]
@daffl I had a look through the rest of the API's delete/remove method calls and I couldn't see any that require extra params, so this should be it 😁

**Comment by wdmtech** [comment]
Saying that, I'll have a 2nd look through just in case

**Comment by wdmtech** [comment]
Had another look through the docs - all I can find is:

SubscriptionItems https://stripe.com/docs/api#delete_subscription_item

Which isn't currently supported anyway.

**Pull request merged**
